feat: switch to BorrowTab
corndao/aave-v3-bos-app pull request #27
Opened 2023-06-20 08:16 UTC by SteveYuOWO

2023-06-29 13:20 UTC, think-in-universe commented on src/AAVE/Modal/RepayModal.jsx
> +                        left: <PurpleTexture>Health factor</PurpleTexture>,
```suggestion
                        left: <PurpleTexture>Health Factor</PurpleTexture>,
```

2023-06-29 13:20 UTC, think-in-universe commented on src/AAVE/Modal/BorrowModal.jsx
> +                        left: <PurpleTexture>Health factor</PurpleTexture>,
```suggestion
                        left: <PurpleTexture>Health Factor</PurpleTexture>,
```

2023-06-29 13:37 UTC, think-in-universe requested changes

2023-06-29 13:37 UTC, think-in-universe commented on src/AAVE/Modal/RepayModal.jsx
> +                  msg: `You repaied ${Big(amount)
```suggestion
                  msg: `You repaid ${Big(amount)
```

2023-06-29 13:37 UTC, think-in-universe commented on src/AAVE/Modal/RepayModal.jsx
> +                msg: `You repaied ${Big(amount)
```suggestion
                msg: `You repaid ${Big(amount)
```

2023-06-29 13:40 UTC, SteveYuOWO commented on src/AAVE/Modal/BorrowModal.jsx
> +  // TODO replace address
Forgot deleted. Already replaced. The address is a constant `0xabc...` value before.

2023-07-06 06:18 UTC, think-in-universe requested changes

2023-07-06 06:18 UTC, think-in-universe commented on src/AAVE.jsx
> +          JSON.stringify(prevYourBorrows) === JSON.stringify(yourBorrows)
Is LINE 542 necessary for updating supplies data?

2023-07-06 09:57 UTC, think-in-universe approved these changes

2023-07-06 09:57 UTC, think-in-universe approved these changes

2023-07-06 09:57 UTC, merged